### ISSUE TITLE
./manage build not working

### ISSUE THREAD

**Issue by kagile** [bcgov/dFlow#205]
Getting this error after `./manage build`

`Invalid interpolation format for "environment" option in service "agri-agent": "${TOB_API_URL:-}"`

Sry, I'm a beginner. Am I missing something?

**Comment by kagile** [comment]
https://github.com/docker/compose/issues/2507 Solved the issue.

**Comment by swcurran** [comment]
@kagile - how did you solve the issue?  Anything we should change in the code or documentation?

Thanks

**Comment by kagile** [comment]
@swcurran As pointed out in comment, $ is  a special character, and needs to be escaped. You may need to update below script:
https://github.com/bcgov/dFlow/blob/042a87bb30ebd2014395f2f36f11ccedd2c2ea15/docker/manage#L110
