### ISSUE TITLE
Update the UI to match this model

### ISSUE THREAD

**Issue by swcurran** [bcgov/dFlow#215]
Please use the screenshots here to update the dFlow pages.

https://docs.google.com/document/d/177-T858cIny58Fctt5l3DYC_RnDWSuYnnDZXbQ7kkaM/edit?usp=sharing

The updates include:

1. Adding help text on the pages.
2. Adjusting the colours and the layout of the graph - minimally.  The key changes:
     1. Putting the title and the action buttons in separate blocks in the header
     1. Centering the title in it's part of the header
     1. Removing the use of the blue colour entirely - just use Red/Yellow/Green
3. Add About page (included), add FAQ page - contents TBD and Contact Us - use one similar to OrgBook.

In parallel, we'll be experimenting with the Schema Names to make them look good.  TBD is if we can have spaces in the Schema Name.

NOTE: The Yellow/White contrast is insufficient right now, that may be updated as you go, or you should update it to something nice.

We'd like this launched in time for the Indy Workshop on Monday, March 11 - along with a reset ledger.

**Comment by carolhoward** [comment]
![greenlight logo](https://user-images.githubusercontent.com/17622005/53768608-2fd0c500-3e8e-11e9-888e-6ec5667ca27c.png)

**Comment by carolhoward** [comment]
Proposed new yellow: #e3a82b

**Comment by carolhoward** [comment]
green = 6aa84fff
red = ff0000ff

**Comment by esune** [comment]
Thanks for the image and color codes @carolhoward! :)
