### ISSUE TITLE
Remove agent persistent storage

### ISSUE THREAD

**Issue by esune** [bcgov/dFlow#225]
We don't need the persistent storage in the agents since we are using the postgresql plugin, we can delete the persistent storage claims and free up some space.

- remove persistent storage claims in OpenShift
- remove persistent storage from templates
- update OpenShift `manage` script and remove step to delete wallets on persistent storage

**Comment by WadeBarnes** [comment]
Reviewed and merged configuration template changes.

@esune, you'll also want to remove the unused parameters from teh `*.param` files.

**Comment by WadeBarnes** [comment]
Reviewed OpenShift environments and confirmed the PVCs have been released.

**Comment by WadeBarnes** [comment]
`*.param` files were updated in https://github.com/bcgov/dFlow/pull/227
